gpio_switch: 17
gpio_led: 18
cameras:
  -
    name: "My camera 0"
    device: /dev/video0
    token: Camera 0's token
    fingerprint: Fingerprint - between 16 and 64 characters
    resolutionx: 1920
    resolutiony: 1080
endpoints:
  -
    name: "Prusa Connect"
    interval: 30
    snapshot_url: https://connect.prusa3d.com/c/snapshot
    info_url: https://connect.prusa3d.com/c/info